apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: lwtdemo-cronjob
  namespace: lwtdemo
spec:
  schedule: "@once"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: lwtdemo-cron
            image: 781127853046.dkr.ecr.us-west-1.amazonaws.com/lwt-ecr-dev-cron:latest
            imagePullPolicy: Always
          restartPolicy: OnFailure