apiVersion: batch/v1
kind: Job
metadata:
  name: lwtdemo-python-job
  namespace: lwtdemo
spec:
  template:
    spec:
      containers:
        - name: lwtdemo-job
          image: your-account-id.dkr.ecr.us-west-1.amazonaws.com/lwt-ecr-dev-cron:latest
          command: ["python", "cronjob.py"]
          env:
            - name: POSTGRES_URI
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: postgres_uri
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: aws_access_id
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: aws_secret_access_key
      restartPolicy: Never
  backoffLimit: 0